theme: jekyll-theme-cayman
- name: Cache Go modules
  uses: actions/cache@v2
  with:
    path: |
      ~/.cache/go-build
      ${{ github.workspace }}/go/pkg/mod
    key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    restore-keys: |
      ${{ runner.os }}-go-
